// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu3PBi5A89V2OH3AonVZngMe4ZSWrB-mo',
    appId: '1:112476175005:web:da386cd489799ccb0ff274',
    messagingSenderId: '112476175005',
    projectId: 'mitaan-fea0b',
    authDomain: 'mitaan-fea0b.firebaseapp.com',
    storageBucket: 'mitaan-fea0b.firebasestorage.app',
    measurementId: 'G-P6S3MJEFXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ctoRl_AJZiOXg9oR70DScRXWWvsQYBs',
    appId: '1:112476175005:android:e75f5efddd73cb8b0ff274',
    messagingSenderId: '112476175005',
    projectId: 'mitaan-fea0b',
    storageBucket: 'mitaan-fea0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Em4-EJpgbG722ftzHNH_GevALZwJjMg',
    appId: '1:112476175005:ios:d5d98c0ec2e3761b0ff274',
    messagingSenderId: '112476175005',
    projectId: 'mitaan-fea0b',
    storageBucket: 'mitaan-fea0b.firebasestorage.app',
    androidClientId: '112476175005-0oi14667ofnp1jq545ijhm3lbdbgbbj2.apps.googleusercontent.com',
    iosClientId: '112476175005-g4vs5t2sqg741rkfl7fembsaicljcudl.apps.googleusercontent.com',
    iosBundleId: 'com.example.proximarketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Em4-EJpgbG722ftzHNH_GevALZwJjMg',
    appId: '1:112476175005:ios:d5d98c0ec2e3761b0ff274',
    messagingSenderId: '112476175005',
    projectId: 'mitaan-fea0b',
    storageBucket: 'mitaan-fea0b.firebasestorage.app',
    androidClientId: '112476175005-0oi14667ofnp1jq545ijhm3lbdbgbbj2.apps.googleusercontent.com',
    iosClientId: '112476175005-g4vs5t2sqg741rkfl7fembsaicljcudl.apps.googleusercontent.com',
    iosBundleId: 'com.example.proximarketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu3PBi5A89V2OH3AonVZngMe4ZSWrB-mo',
    appId: '1:112476175005:web:5863406cf3fc44350ff274',
    messagingSenderId: '112476175005',
    projectId: 'mitaan-fea0b',
    authDomain: 'mitaan-fea0b.firebaseapp.com',
    storageBucket: 'mitaan-fea0b.firebasestorage.app',
    measurementId: 'G-XPNP7LM0FM',
  );
}
