// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHxsOJ07v57Wxpf_q2Jn_6Jmbre1SJTzs',
    appId: '1:725230005160:web:0554f9bc29d4b6c6110b9d',
    messagingSenderId: '725230005160',
    projectId: 'proximarket-e9d41',
    authDomain: 'proximarket-e9d41.firebaseapp.com',
    storageBucket: 'proximarket-e9d41.firebasestorage.app',
    measurementId: 'G-8D8BWDNHMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNJ44119AvMnIsmonzkqLv0zXyekUycj4',
    appId: '1:725230005160:android:0c6e30a25f9e12d9110b9d',
    messagingSenderId: '725230005160',
    projectId: 'proximarket-e9d41',
    storageBucket: 'proximarket-e9d41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaf0rWaNBviv79AlP_A39WbGu1hBbNUPg',
    appId: '1:725230005160:ios:b4a79cfa353570ca110b9d',
    messagingSenderId: '725230005160',
    projectId: 'proximarket-e9d41',
    storageBucket: 'proximarket-e9d41.firebasestorage.app',
    iosClientId: '725230005160-j28gbiab0omp4deuufsv0t7hcgr1u6f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.proximarketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaf0rWaNBviv79AlP_A39WbGu1hBbNUPg',
    appId: '1:725230005160:ios:b4a79cfa353570ca110b9d',
    messagingSenderId: '725230005160',
    projectId: 'proximarket-e9d41',
    storageBucket: 'proximarket-e9d41.firebasestorage.app',
    iosClientId: '725230005160-j28gbiab0omp4deuufsv0t7hcgr1u6f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.proximarketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHxsOJ07v57Wxpf_q2Jn_6Jmbre1SJTzs',
    appId: '1:725230005160:web:a05b8b8798002ece110b9d',
    messagingSenderId: '725230005160',
    projectId: 'proximarket-e9d41',
    authDomain: 'proximarket-e9d41.firebaseapp.com',
    storageBucket: 'proximarket-e9d41.firebasestorage.app',
    measurementId: 'G-RK7WCSFVD1',
  );
}
