name: mitan_app
description: MitaAn — Plateforme locale de services et de vente avec géolocalisation
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.11.0

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.3.0
  firebase_storage: ^12.4.10
  google_sign_in: ^6.0.0
  provider: ^6.0.0
  image_picker: ^1.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.6.0
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.3.0   # Requis ici si tu appelles FlutterNativeSplash.preserve() au runtime
  firebase_crashlytics: ^4.0.0    # Obligatoire dans dependencies pour initialiser le tracking dans le code

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints
  flutter_lints: ^6.0.0

  # Outils de génération d'icônes et d'écrans de démarrage
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.3.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is included
  uses-material-design: true

  # === Configuration des assets ===
  assets:
    - assets/images/

# === Configuration des icônes de l'application ===
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

# === Configuration du Splash Screen ===
flutter_native_splash:
  color: "#1D9E75"
  android: true
  ios: true